cmake -DCMAKE_INSTALL_PREFIX=/usr/local/mysql80 -DMYSQL_DATADIR=/usr/local/mysql80/data -DWITH_BOOST=boost -DFORCE_INSOURCE_BUILD=ON

cmake -DCMAKE_INSTALL_PREFIX=/usr/local/mysql80 -DMYSQL_DATADIR=/usr/local/mysql80/data -DWITH_BOOST=boost -DFORCE_INSOURCE_BUILD=ON -DWITH_DEBUG=1
